groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns=[

    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='new'),
    path('post/in/<slug>/',views.SingleGroup.as_view(),name='detail'),
    path('join/<slug>/',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>/',views.LeaveGroup.as_view(),name='leave')
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns=[

        path('',views.PostList.as_view(),name='all'),
        path('new/',views.CreatePost.as_view(),name='new'),
        path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
        path('by/<username>/<int:pk>/',views.PostDetail.as_view(),name='detail'),
        path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete'),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.HomePage.as_view(),name="index"),
    path('admin/', admin.site.urls),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('groups/',include('groups.urls', namespace='groups')),
    path('posts/',include('posts.urls', namespace='posts')),
]

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.
import misaka

from django.contrib.auth import get_user_model
User=get_user_model()

class Group(models.Model):
    name = models.CharField(max_length=150,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through="GroupMembers")

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug=slugify(self.name)
        self.description_html=misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:detail',kwargs={'slug':self.slug})

    class Meta:
        ordering=['name']


class GroupMembers(models.Model):
    group = models.ForeignKey(Group,on_delete=models.CASCADE,related_name='memberships')
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together=('group','user')

groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.urls import reverse
from django.views.generic import (ListView,DetailView,
                                  CreateView,RedirectView)
from .models import Group,GroupMembers
from django.contrib import messages
from django.shortcuts import get_object_or_404
# Create your views here.

class CreateGroup(LoginRequiredMixin,CreateView):
    model=Group
    fields=('name','description')

class SingleGroup(LoginRequiredMixin,DetailView):
    model=Group

class ListGroups(LoginRequiredMixin,ListView):
    model=Group

class JoinGroup(LoginRequiredMixin,RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse ('groups:detail',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

        try:
            GroupMembers.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,"Warning! You are already a member of {}".format(group.name))

        else:
            messages.success(self.request,"Welcome! You are now a member of {}".format(group.name))

        return super().get(request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin,RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse ('groups:detail',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        try:
            membership = GroupMembers.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()

        except GroupMembers.DoesNotExist:
            messages.warning(self.request,"You can't leave this group because you aren't in it.")

        else:
            membership.delete()
            messages.success(self.request,"You have successfully left this group.")

        return super().get(request,*args,**kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}
  {% block content %}
    <div class="container">
      <div class="row">
        {% block pregroup %} {% endblock %}
        {% block groupcontent %} {% endblock %}
        {% block postgroup %} {% endblock %}
      </div>
    </div>
  {% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

  {% block pregroup %}
    <!-- <div class="container"> -->
      <div class="col-md-4">
        <h1>{{group.name}}</h1>
        <hr>
        <h4>Member{{group.members.count|pluralize}}: {{group.members.count}}</h4>

        {% if user in group.members.all %}
          <a href="{% url 'posts:new' %}" class='btn btn-primary'>
            <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Create New Post</a>

          <a href="{% url 'groups:leave' slug=group.slug %}" class='btn btn-danger'>
            <i class="fa fa-times" aria-hidden="true"></i> Leave</a>
            <br>
            <br>
              {% for message in messages %}
                {{ message }}
              {% endfor %}
        {% else %}
          <a href="{% url 'groups:join' slug=group.slug %}" class='btn btn-warning'>
            <i class="fa fa-user-plus" aria-hidden="true"></i> Join</a>
            <br>
            <br>
              {% for message in messages %}
                {{ message }}
              {% endfor %}
        {% endif %}
      </div>
    <!-- </div> -->
   {% endblock %}

   {% block groupcontent %}
     <div class="col-md-8">
       <div class="scrollstyle">
         <br>
       {% if group.posts.count == 0 %}
        <h1>No Posts yet!</h1>
      {% else %}
        {% for post in group.posts.all %}
          {% include 'posts/_post.html' %}
        {% endfor %}
      {% endif %}
      </div>
     </div>
   {% endblock %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
 {% load bootstrap4 %}

 {% block pregroup %}
    <div class="container">
      <h1>Create a New Group:</h1>
    </div>
 {% endblock %}


  {% block groupcontent %}
     <div class="col-md-8">
       <form method="post">
         {% csrf_token %}
         {% bootstrap_form form %}
         <button type="submit" class="btn btn-primary btn-lg">
           <i class="fa fa-check" aria-hidden="true"></i> Create</button>
       </form>
     </div>
  {% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}
  {% block pregroup %}
    <div class="col-md-4">
      <br>
      {% if user.is_authenticated %}
          <h2>Welcome back
              <a href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a>
          </h2>
      {% endif %}
      <hr>
      <div class="container">
        <h4>Welcome to Group List</h4>
        <h6>Select a Group with a shared interest!</h6>
        <br>
        {% if user.is_authenticated %}
            <a href="{% url 'groups:new' %}" class='btn btn-lg btn-warning'>
              <i class="fa fa-plus" aria-hidden="true"></i> Create New Group</a>
        {% endif %}
      </div>
    </div>
  {% endblock %}

  {% block groupcontent %}
    <div class="col-md-8">
      <div class="container">
        <div class="scrollstyle">
          <br>
          {% for grp in group_list %}
            <a href="{% url 'groups:detail' slug=grp.slug %}">
              <h1>{{grp.name}}</h1> </a>
              <p>{{grp.description_html|safe}}</p>
              <div class="col-md-4">
                <h6>Member{{grp.members.count|pluralize}}: {{grp.members.count}}
                    <br>Post{{grp.posts.count|pluralize}}: {{grp.posts.count}} </h6>
              </div>
              <hr>
          {% empty %}
            <h1>No Groups created yet.</h1>
          {% endfor %}
        </div>
      </div>
    </div>
  {% endblock %}