accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns=[

    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns=[

        path('',views.PostList.as_view(),name='all'),
        path('new/',views.CreatePost.as_view(),name='new'),
        path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
        path('by/<username>/<int:pk>/',views.PostDetail.as_view(),name='detail'),
        path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete'),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.HomePage.as_view(),name="index"),
    path('admin/', admin.site.urls),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('groups/',include('groups.urls', namespace='groups')),
    path('posts/',include('posts.urls', namespace='posts')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>STAR SOCIAL</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
     integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
     crossorigin="anonymous">
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
     integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
     crossorigin="anonymous"></script>

     <!-- CSS -->
     <link rel="stylesheet" href="{% static 'simplesocial/master.css' %}">

     <!-- Custom Fonts -->
     <link href="https://fonts.googleapis.com/css?family=Acme|Josefin+Sans&display=swap" rel="stylesheet">

     <!-- Glyphicons -->
     <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  </head>
  <body>
    <!-- <canvas id="canvas"></canvas> -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
          <div class="container">

            <a class="navbar-brand" href="{% url 'index' %}">Star Social</a>
            <div class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
              
                <a class="nav-item active nav-link btn btn-simple" href="{% url 'posts:all' %}">
                  <i class="fa fa-file-o" aria-hidden="true"></i> Posts</a>

                <a class="nav-item active nav-link btn btn-simple" href="{% url 'groups:all' %}">
                  <i class="fa fa-users" aria-hidden="true"></i> Groups</a>

                <a class="nav-item active nav-link btn btn-simple" href="{% url 'groups:new' %}">
                  <i class="fa fa-plus" aria-hidden="true"></i> Group</a>

                <a class="nav-item active nav-link btn btn-simple" href="{% url 'accounts:logout' %}">
                  <i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a>

              {% else %}

                <a class="nav-item active nav-link btn btn-simple" href="{% url 'groups:all' %}">
                  <i class="fa fa-users" aria-hidden="true"></i> Groups</a>

                <a class="nav-item active nav-link btn btn-simple" href="{% url 'accounts:login' %}">
                  <i class="fa fa-user-plus" aria-hidden="true"></i> Login</a>

                <a class="nav-item active nav-link btn btn-simple" href="{% url 'accounts:signup' %}">
                  <i class="fa fa-plus" aria-hidden="true"></i> Sign Up</a>

              {% endif %}
            </ul>

        </div>
      </nav>

      <div class="container">
        {% block content %}
        {% endblock %}
      </div>

     <canvas id="canvas"></canvas>
      <script type="text/javascript" src="{% static 'simplesocial/style.js' %}"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
  {% block content %}
  <br>
  <h1 align='center'>Welcome to Star Social !</h1>
  <br>
  <h4 align='center'>This is a Social Group Site where you can SignUp and create your
  own groups or even join in the existing groups! You can add posts, articles or your messages
  in any group you wish to join.
  <br>
  <hr>
  Hope you'll enjoy your experience </h4>
  {% endblock %}

templates/test.html
{% extends 'base.html' %}
  {% block content %}
    <br>
    <h1 align='center'>Welcome! You are successfully logged in.</h1>
  {% endblock %}

templates/thanks.html
{% extends 'base.html' %}
  {% block content %}
    <br>
    <h1 align='center'>Thanks for visiting! Come back soon!</h1>
  {% endblock %}