posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns=[

        path('',views.PostList.as_view(),name='all'),
        path('new/',views.CreatePost.as_view(),name='new'),
        path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
        path('by/<username>/<int:pk>/',views.PostDetail.as_view(),name='detail'),
        path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete'),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.HomePage.as_view(),name="index"),
    path('admin/', admin.site.urls),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('groups/',include('groups.urls', namespace='groups')),
    path('posts/',include('posts.urls', namespace='posts')),
]

posts/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
import misaka

from groups.models import Group

from django.contrib.auth import get_user_model
User=get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='posts')
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group,on_delete=models.CASCADE,related_name='posts',null=True,blank=True)

    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        self.message_html=misaka.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:detail',kwargs={'username':self.user.username,'pk':self.pk})

    class Meta:
        ordering=['-created_at']
        unique_together=['user','message']

posts/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import Http404
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from braces.views import SelectRelatedMixin

from .models import Post
from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

class PostList(SelectRelatedMixin,generic.ListView):
    model = Post
    select_related = ('user','group')

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['other_groups'] = Group.objects.exclude(members__in=[self.request.user])
        context['member_groups'] = Group.objects.filter(members__in=[self.request.user])
        return context

class UserPosts(generic.ListView):
    model = Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(
                username__iexact = self.kwargs.get('username')
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin,generic.DetailView):
    model = Post
    select_related = ('user','group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
                    user__username__iexact = self.kwargs.get('username')
        )

class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    model = Post
    fields = ('group','message')

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = Post
    select_related = ('user','group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,"Post Deleted!!")
        return super().delete(*args,**kwargs)

posts/templates/posts/_post.html
<!-- <div class="col-md-8"> -->
<br>
  <div class="main_content">
    <h3>
      <a href="{% url 'posts:for_user' username=post.user.username %}">@{{post.user.username}}</a>
      {{post.message_html|safe}}
    </h3>
      <div class="container">
        <h6>
          <time><a href="{% url 'posts:detail' username=post.user.username pk=post.pk %}">{{post.created_at}}</a></time>
          <br>
          {% if post.group %}
            <a href="{% url 'groups:detail' slug=post.group.slug %}">In {{post.group.name}}</a>
          {% endif %}

          {% if user.is_authenticated and post.user == user and not hide_delete %}
            <a href="{% url 'posts:delete' pk=post.pk %}" class='btn btn-danger delbtn'>
            <i class="fa fa-trash" aria-hidden="true"></i></a>
          {% endif %}
        </h6>
    </div>
    <hr>
  </div>
<!-- </div> -->

posts/templates/posts/post_base.html
{% extends 'base.html' %}
  {% block content %}
    <div class="container">
      <div class="row">
        {% block pre_body %} {% endblock %}
        {% block body %} {% endblock %}
        {% block post_body %} {% endblock %}
      </div>
    </div>
  {% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}
  {% block pre_body %}
    <div class="col-md-4">
      <h2>Are you sure you want to delete the post?</h2>
    </div>
  {% endblock %}

  {% block body %}
    <!-- <div class="container"> -->
      <div class="col-md-8">
        {% include 'posts/_post.html' with post=object hide_delete=True %}

        <form method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-lg btn-danger">
              <i class="fa fa-trash" aria-hidden="true"></i> Confirm</button>
              
          <a href="{% url 'posts:detail' username=user.username pk=post.pk %}" class="btn btn-lg btn-warning">
              <i class="fa fa-reply" aria-hidden="true"></i> Cancel</a>
        </form>
      </div>
    <!-- </div> -->
  {% endblock %}

posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}
  {% block pre_body %}
    <div class="col-md-2">
    </div>
  {% endblock %}

  {% block body %}
    <div class="col-md-8">
      {% include 'posts/_post.html' %}
    </div>
  {% endblock %}

posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
  {% load bootstrap4 %}

  {% block pre_body %}
    <div class="col-md-4">
      <div class="container">
        <h1>Create New Post:</h1>
      </div>
    </div>
  {% endblock %}

  {% block body %}
    <div class="col-md-8">
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary btn-lg">
          <i class="fa fa-check" aria-hidden="true"></i> Create Post</button>
      </form>
    </div>

  {% endblock %}

posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}
  {% block pre_body %}
    <div class="col-md-4">
      <br>
      {% if request.user.is_authenticated %}
        <h3>Your Groups:</h3>
        <ul>
          {% for member_group in member_groups %}
            <li>
              <h5><a href="{% url 'groups:detail' slug=member_group.slug %}">{{member_group.name}}</a></h5>
            </li>
          {% empty %}
              <h5>Not a member of any group!</h5>
          {% endfor %}
        </ul>
      {% endif %}
      <hr>
      <h3>Other Groups:</h3>
      <ul>
        {% for othergroup in other_groups %}
          <li>
            <h5><a href="{% url 'groups:detail' slug=othergroup.slug %}">{{othergroup.name}}</a></h5>
          </li>
       {% empty %}
          <h5>No other group.</h5>
       {% endfor %}
      </ul>
    </div>
  {% endblock %}

  {% block body %}
    <div class="col-md-8">
      <div class="scrollstyle">
        {% for post in post_list %}
          {% include 'posts/_post.html' %}
        {% endfor %}
      </div>
    </div>
  {% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block pre_body %}
<div class="col-md-4">
	<h1>@{{ post_user.username }}</h1>
	<h4>Post History:</h4>
</div>
{% endblock %}

{% block body %}
<div class="col-md-8">
	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% empty %}
			<h5>No posts yet.</h5>
	{% endfor %}
</div>
{% endblock %}